name: Auto Tag on Commit

on:
  push:
    branches:
      - SB

jobs:
  build_no_release:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          
      - name: Generate Git Tag
        id: generate_tag
        run: |
          # Find the latest tag with the _QA suffix if available
          LATEST_QA_TAG=$(git describe --tags --match "*_QA" --abbrev=0 || echo "")

          if [ -z "$LATEST_QA_TAG" ]; then
            # If no _QA tags found, start with initial version and branch name
            NEW_TAG="V1.0.0_${GITHUB_REF#refs/heads/}"
          else
            # Extract the version number from the latest _QA tag
            VERSION=$(echo "$LATEST_QA_TAG" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

            # Construct the new _SB tag
            NEW_TAG="V${VERSION}_${GITHUB_REF#refs/heads/}"
          fi

          echo "Generated new _SB tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        run: |
          git config user.name "Abisheck2002"
          git config user.email "abisheck.g@netxd.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
