name: Auto Tag on Commit

on:
  push:
    branches:
      - SB

jobs:

  build_no_release:
      runs-on: ubuntu-latest
      
      steps:
              - name: Checkout repository
                uses: actions/checkout@v2
                with:
                  fetch-depth: '0'
          
              - name: Generate Git Tag
                id: generate_tag
                run: |
                  # Find the latest tag with the _QA suffix if available
                  LATEST_QA_TAG=$(git describe --tags --match "*_QA" --abbrev=0 || echo "")
          
                  if [ -z "$LATEST_QA_TAG" ]; then
                    # If no _QA tags found, start with initial version and branch name
                    NEW_TAG="V1.0.0_${GITHUB_REF#refs/heads/}_QA"
                    
                  else
                    # Extract the version number and branch name from the latest _QA tag
                    VERSION_BRANCH=$(echo "$LATEST_QA_TAG" | cut -d'_' -f1)
                    VERSION=$(echo "$VERSION_BRANCH" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
                    BRANCH_NAME=$(echo "$LATEST_QA_TAG" | cut -d'_' -f2)
          
                    # Increment the version number
                    NEW_VERSION=$(echo "$VERSION" | awk -F'.' '{print $1 "." $2 "." $3 }')
          
                    # Construct the new _QA tag
                    NEW_TAG="V${NEW_VERSION}_${GITHUB_REF#refs/heads/}_SB"
                  fi
          
                  echo "Generated new _QA tag: $NEW_TAG"
                  echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          
              - name: Push Git Tag
                run: |
                  git config user.name "Abisheck2002"
                  git config user.email "abisheck.g@netxd.com"
                  git tag $NEW_TAG
                  git push origin $NEW_TAG
          