name: Create QA Tag

on:
  push:
    branches:
      - main

jobs:
  create_qa_tag:
    name: Create QA Tag
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create QA branch
      run: git checkout -b QA

    - name: Get latest tag version
      id: get_tag
      run: echo ::set-output name=latest_tag::$(git describe --tags --abbrev=0)

    - name: Extract version number
      id: extract_version
      run: echo ::set-output name=latest_version::${{ steps.get_tag.outputs.latest_tag | replace('V0.0.','') | split('_')[0] }}

    - name: Increment version number
      id: increment_version
      run: echo ::set-output name=next_version::$((${{ steps.extract_version.outputs.latest_version }} + 1))

    - name: Create new tag
      id: create_tag
      run: |
        next_version=${{ steps.increment_version.outputs.next_version }}
        git tag "V0.0.${next_version}_QA"
        git push origin "V0.0.${next_version}_QA"
        echo "New tag created: V0.0.${next_version}_QA"
