name: Create QA Tag

on:
  push:
    branches:
      - main

jobs:
  create_qa_tag:
    name: Create QA Tag
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create QA branch
      run: git checkout -b QA

    - name: Get latest tag version
      id: get_tag
      run: echo ::set-output name=latest_tag::$(git describe --tags --abbrev=0)

    - name: Create new tag
      id: create_tag
      run: |
        latest_version=$(echo "${{ steps.get_tag.outputs.latest_tag }}" | cut -d'.' -f3 | cut -d'_' -f1)
        next_version=$((latest_version + 1))
        new_tag="V0.0.${next_version}_QA"
        git tag "$new_tag"
        git push origin "$new_tag"
        echo "New tag created: $new_tag"
