name: Auto Tag on Commit

on:
  push:
    branches:
      - SB

jobs:
  build_no_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'refs/tags/*'

      - name: Get latest tag from QA branch
        id: get_latest_tag
        run: |
          git fetch --tags origin QA
          LATEST_TAG=$(git describe --tags --abbrev=0 origin/QA)
          echo "Latest tag in QA branch: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Checkout SB branch
        run: git checkout SB

      - name: Generate Git Tag
        id: generate_tag
        run: |
          # Extract the version number and branch name from the latest tag
          VERSION_BRANCH=$(echo "$LATEST_TAG" | cut -d'_' -f1)
          VERSION=$(echo "$VERSION_BRANCH" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

          # Increment the version number
          NEW_VERSION=$(echo "$VERSION" | awk -F'.' '{print $1 "." $2 "." $3}')

          # Construct the new tag with the desired branch name
          NEW_TAG="V${NEW_VERSION}_SB"

          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        run: |
          git config user.name "Abisheck2002"
          git config user.email "abisheck.g@netxd.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
