name: Auto Tag on Commit

on:
  push:
    branches:
      - QA  # Adjust this to the branch you want to tag

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "Abisheck2002"
          git config user.email "abisheck.g@netxd.com"

      - name: Get the latest tag
        id: get-latest-tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Get previous tag
        id: get_previous_tag
        run: |
          previous_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
          echo "Previous version: $previous_tag"
      
      - name: Bump version
        id: bump_version
        run: |
          # Extract the previous tag
          previous_tag="${{ steps.get_previous_tag.outputs.previous_tag }}"
          
          # Extract the version number
          version="${previous_tag##*/V.}"
          echo "Version $version"
          
          # Increment the version (assuming it follows semantic versioning X.Y.Z)
          IFS='.' read -r major minor patch <<< "$version"
          patch=$((patch + 1))
          new_version="${major}.${minor}.${patch}_QA"
          
          echo "New Version = $new_version"

      - name: Tag and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_tag="V.${{ steps.bump_version.outputs.new_version }}"
          git tag "$new_tag"
          git push origin "$new_tag"
