name: Auto Tag on Commit

on:
  push:
    branches:
      - SB

jobs:
  build_no_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Generate Git Tag
        id: generate_tag
        run: |
          # Find the latest tag if available
          LATEST_TAG=$(git describe --tags --abbrev=0)

          if [ -z "$LATEST_TAG" ]; then
            echo "No tags found. Starting with initial version."
            NEW_TAG="V1.0.0_SB"
          else
            # Extract the version number and branch name from the latest tag
            VERSION_BRANCH=$(echo "$LATEST_TAG" | cut -d'_' -f1)
            VERSION=$(echo "$VERSION_BRANCH" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')

            # Increment the version number
            MAJOR=$(echo "$VERSION" | cut -d'.' -f1)
            MINOR=$(echo "$VERSION" | cut -d'.' -f2)
            PATCH=$(echo "$VERSION" | cut -d'.' -f3)
            

            # Construct the new tag with the desired branch name
            NEW_TAG="V${MAJOR}.${MINOR}.${NEW_PATCH}_SB"
          fi

          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.name "Abisheck2002"
          git config --global user.email "abisheck.g@netxd.com"

      - name: Push Git Tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
