name: Auto Tag on Commit

on:
  push:
    branches:
      - SB
  

jobs:
  build_SB_PULL_REQUEST:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Generate Git Tag
        id: generate_tag
        run: |
          # Find the latest tag if available
          if [ "${{ github.event_name }}" == "push" ]; then
            LATEST_TAG=$(git describe --tags --abbrev=0 "origin/QA" || echo "")
    
          fi

          # If no tag found
          if [ -z "$LATEST_TAG" ]; then
            # If no tags found, start with initial version and branch name
            if [ "${{ github.event_name }}" == "push" ]; then
              if [ "${{ github.ref }}" == "refs/heads/QA" ]; then
                NEW_VERSION="1.0.0"
              else
                NEW_VERSION="1.0.0.P1"
              fi
            fi
          else
            # Extract the version number and branch name from the latest tag
            VERSION_BRANCH=$(echo "$LATEST_TAG" | cut -d'_' -f1)
            VERSION=$(echo "$VERSION_BRANCH" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
            BRANCH_NAME=$(echo "$LATEST_TAG" | cut -d'_' -f2)
            
            # Increment the version number
            NEW_VERSION=$(echo "$VERSION" | awk -F'.' '{print $1 "." $2 "." $3}')

            # Construct the new tag
            if [ "${{ github.event_name }}" == "push" ]; then
              if [ "${{ github.ref }}" == "refs/heads/QA" ]; then  # Changed 'github.head_ref' to 'github.base_ref'
                NEW_TAG="V${NEW_VERSION}_${GITHUB_REF#refs/heads/}"    # Changed 'github.head_ref' to 'GITHUB_REF'
              else
                NEW_TAG="V${NEW_VERSION}.P1_${GITHUB_REF#refs/heads/}"  # Changed 'github.head_ref' to 'GITHUB_REF'
              fi
            fi
          fi

          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        run: |
          git config user.name "Abisheck2002"
          git config user.email "abisheck.g@netxd.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
