name: Auto Tag on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - SB

jobs:
  build_SB_PULL_REQUEST:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Extract Branch Names
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          HEAD_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Base ref: $BASE_BRANCH"
          echo "Head ref: $HEAD_BRANCH"

      # Your other workflow steps...