name: Auto Tag on Commit

on:
  push:
    branches:
      - SB

jobs:
  build_SB_PULL_REQUEST:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Generate Git Tag
        id: generate_tag
        run: |
          # Extract the base and head branches from the push event payload
          BASE_BRANCH=$(echo "${{ github.ref }}" | sed 's|.*/||')  # Extract branch name from ref
          HEAD_BRANCH=$(git rev-parse --abbrev-ref HEAD)  # Get current branch name

          # Your existing logic for generating tags goes here...
          
          echo "Base ref: $BASE_BRANCH"
          echo "Head ref: $HEAD_BRANCH"

          # Modify your logic to use BASE_BRANCH and HEAD_BRANCH accordingly
          
          # Example:
          # if [ "$HEAD_BRANCH" == "QA" ]; then
          #   NEW_TAG="V${NEW_VERSION}_${BASE_BRANCH}"
          # else
          #   NEW_TAG="V${NEW_VERSION}.P1_${BASE_BRANCH}"
          # fi
          
          # echo "Generated new tag: $NEW_TAG"
          # echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      # Rest of your workflow steps...